// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF3d8y_037BPaEA4WfQA-ASA7PsrOP8FM',
    appId: '1:447213714400:web:f78fbf91f6cdc188174985',
    messagingSenderId: '447213714400',
    projectId: 'food-panda-d98f9',
    authDomain: 'food-panda-d98f9.firebaseapp.com',
    storageBucket: 'food-panda-d98f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcKkGKBdMMlMTK7OCYqYU1W516ms1PgHg',
    appId: '1:447213714400:android:96f2bfa44920a394174985',
    messagingSenderId: '447213714400',
    projectId: 'food-panda-d98f9',
    storageBucket: 'food-panda-d98f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpy6-vS3VHkojROoAGuMNm3JuFUA-jvEU',
    appId: '1:447213714400:ios:b09621155c792e71174985',
    messagingSenderId: '447213714400',
    projectId: 'food-panda-d98f9',
    storageBucket: 'food-panda-d98f9.appspot.com',
    iosBundleId: 'com.example.foodPanda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpy6-vS3VHkojROoAGuMNm3JuFUA-jvEU',
    appId: '1:447213714400:ios:6d295e1d2faa4311174985',
    messagingSenderId: '447213714400',
    projectId: 'food-panda-d98f9',
    storageBucket: 'food-panda-d98f9.appspot.com',
    iosBundleId: 'com.example.foodPanda.RunnerTests',
  );
}
